In [1]:
# installtion of libraries:

!pip install numpy

In [2]:
# importing the libraries

import numpy as np  

In [6]:
x=np.array([[1,2,3,4]])

In [7]:
print(x)

[[1 2 3 4]]


In [8]:
#  to know the dimensions of array

x.ndim

2

In [15]:
y=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

In [16]:
y.ndim

3

In [22]:
z=np.array([1,2,3,4],ndmin=15)

In [23]:
z.ndim

15

In [24]:
print(z)

[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]


In [53]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [28]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
y=x.copy()

In [32]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [30]:
print(x+y)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [31]:
print(x*y)

[[  1   4   9]
 [ 16  25  36]
 [ 49  64  81]
 [100 121 144]]


In [33]:
a=np.array([[1,2],[3,4]])

In [37]:
b=a.copy()

In [38]:
print(b)

[[1 2]
 [3 4]]


In [39]:
print(a)

[[1 2]
 [3 4]]


In [40]:
print(a*b)

[[ 1  4]
 [ 9 16]]


In [42]:
# indexing in numpy
b[1]

array([3, 4])

In [43]:
x=np.array([1,2,3,4])

In [48]:
x[-2:-1]

array([3])

In [47]:
x[2:4]

array([3, 4])

In [49]:
x[::-1]

array([4, 3, 2, 1])

In [50]:
a.shape

(2, 2)

In [51]:
print(x)

[1 2 3 4]


In [56]:
x.shape

(4, 3)

In [55]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [57]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [59]:
x.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [60]:
x.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [89]:
# random--> captcha
from numpy import random

x=random.randint(10)
print(x)

7


In [123]:
# random--> captcha
from numpy import random

x=random.randint(2,5)
print(x)

2


In [155]:
x=random.randint(50, size=(4,4))
print(x)

[[46 29 49  5]
 [42 34 31 43]
 [22 41 31 35]
 [44  0 12 20]]


In [268]:
dice_1=random.randint(3)
dice_2=random.randint(3)
dice=dice_1+dice_2
print(dice)

2


2
